### ISSUE TITLE
Resume an aborted download

### ISSUE THREAD

**Issue by wtanksleyjr** [ping/odmpy#18]
I just got a TCP disconnect in the middle of a download; I tried and failed to find a way to resume it. It looks like there's some mechanism for using the license file to resume the download ... but if so, what might it take to actually do it? (For now, of course, I just re-download the ODM file.)

**Comment by wtanksleyjr** [comment]
This is probably a feature request, I suppose ... unless it's already a feature, in which case it's just a question :) .

**Comment by ping** [comment]
There isn't a specific resume command. You resume the download process by just running the same command again if the license file is already downloaded or if the odm file has not expired.

It will continue from the last completed download. Any partial download will be discarded.

**Comment by wtanksleyjr** [comment]
I thought I tried that, and I'm not sure why it didn't work (it tried to download the license again) ... I think maybe I know what I did wrong before -- I moved the ODM file. Or something.

Would it be possible to auto-retry for as long as progress is being made? Obviously no point in retrying if 0 bytes are transferred.

**Comment by ping** [comment]
I'm not sure what you mean by
> auto-retry for as long as progress is being made

The license file is stored in the specified download folder (one level up from the book folder), and will be downloaded only if an existing one is not found at the expected location.

The resume function works fairly well in my experience. I use it extensively during testing because I don't often want to re-download all 18 parts of a book while trying to debug an issue.

In any case, I have added retry option `-r`/`--retry` which allows you to specify the number of retries, with a default of 1. This relies on the underlying retry functionality provided by the `requests`/`urllib3` libraries and there are some known limitations. I believe read timeouts are not retried.

This is available from version 0.4.1.

It will help if you can capture the error message should it happen again.

**Comment by wtanksleyjr** [comment]
Oh, cool! That definitely wasn't there when I wrote my script. (Script
functionality is my use case -- I'm using syncthing to move ODMs to my
server, and then odmpy to unwrap them and move the books onto my reading
rotation.) I'll definitely read up and add -r to my command line.

Failures are super-rare so it's very hard to debug them -- right at this
point the only two things my script looks for is an errorlevel or missing
mp3 files (I count the number of files specified in the ODM).

But if I do hit anything again, I'll make a copy of the output.

-Wm

**Comment by wtanksleyjr** [comment]
In my opinion this bug report's been resolved; I've confirmed `-r` fixes the easy resumes, and I've been able to resume some more complex problems.
