### ISSUE TITLE
[Feature] Libby mode places --keepodm files next to MP3s

### ISSUE THREAD

**Issue by wtanksleyjr** [ping/odmpy#27]
When we download and keep the ODM files using that `--keepodm` flag, would it be possible to keep them in the folder with the MP3s, instead of in the current working directory? That would become especially handy when processing multiple books, so I don't lose track of which files go with which book. This wasn't a concern with your old mode of operation when the user provided the ODM file, but when operating in Libby mode things are different.

**Comment by ping** [comment]
It is not quite possible to do that because _before_ the ODM is downloaded and parsed, we don't know _all_ the authors (whose names are needed to create the book folder), we only know the "first creator" which is entirely up to Overdrive to define.

We could possibly move the odm/license files after the download completes but that will cause problems during testing and development. The short version of the problem is that, I'll end up having to always re-download the ODM from Libby while testing/debugging and that is a problem because Libby limits the number of times the ODM can actually be downloaded.

**Comment by wtanksleyjr** [comment]
That's rough, I see what you mean. It probably matters a lot less now that I have the OPF file, so I have a source-of-truth for the metadata.
