### ISSUE TITLE
Downloading with --direct not setting track number

### ISSUE THREAD

**Issue by jvandervort** [ping/odmpy#36]
Downloading with --direct not setting track number

commit 5af3caceb6c4a2e65be4e7dc703674bd89b3be42

Everything else looks fine

**Comment by ping** [comment]
Can you try with `--overwritetags`?

**Comment by jvandervort** [comment]
--overwritetags did correctly set the track number.
Is this expected behavior then? Use --overwritetags if you want tracknumbers on --direct downloads?

**Comment by ping** [comment]
Both `--direct` and odm-based downloads should have the same problem.

Originally, by design, odmpy doesn't write over any existing tag if there is a value in place. So if you don't see any track number in the ID3 tags, it's very likely that the original downloaded mp3 *had some kind of a value* in the tag but it may not be a valid ID3 track number value.

Before `--overwritetags` was introduced, there was no way to change this behavior.  The option simply forces odmpy to ignore the original safeguard and write over existing tags. That is probably why the track number ID3 tag now shows up with the option.

**Comment by jvandervort** [comment]
Sounds good, I'll add `--overwritetags` to my normal workflow.
