### ISSUE TITLE
[Feature] PDF/attached document downloads

### ISSUE THREAD

**Issue by wtanksleyjr** [ping/odmpy#39]
It is possible to download PDF documents attached to the ebook at the same time as downloading the MP3 files, or as a separate followup? I know some are available only as ADE documents, which raises more problems, but I don't even know if it's possible to automatically download any attached documents.

**Comment by ping** [comment]
This is something I've thought about, but I don't often encounter titles with attached documents. I don't know how to search specifically for these types of books either.

If you know of any examples, please post them and I can take a look.

**Comment by wtanksleyjr** [comment]
On Los Angeles Public Library (LAPL):

The Scythian Empire
Blockchain for Everyone
Escape from Model Land
...
OK, that's all I see right now.

I don't see anything obvious in the JSON dump you produce (and BTW, I also don't see things like the Narrator there, does their info source not provide that?), although there's some data that MIGHT correlate to it.

(Side comment: Seriously, Github? You don't support uploading JSON files? Sheesh. I abhor MIME types.)

[books.json.txt](https://github.com/ping/odmpy/files/10887090/books.json.txt)

**Comment by ping** [comment]
I don't think automatically getting the attachment is possible.

From what I can tell, you can get the attachment only from the library overdrive site, so for LAPL that will be at https://lapl.overdrive.com/account/loans.

Libby doesn't seem to have the ability to view/download the attachment which rules out automating this process for now. In fact, from the Libby interface, I cannot even tell that there is an attachment. If in the future, Libby does introduce this, please come back and raise a request.

> I don't see anything obvious in the JSON dump you produce (and BTW, I also don't see things like the Narrator there, does their info source not provide that?), although there's some data that MIGHT correlate to it.

For additional book information, you will have to query the OverDrive API for it. odmpy has an internal OverDrive API client but I'm not going to point you to it since future changes may break your code. It's a fairly simple implementation though.

**Comment by wtanksleyjr** [comment]
That makes perfect sense. Thank you!

**Comment by ping** [comment]
I've just added the ability to download audiobook attachment/supplementary content. Practically all of these attachments are DRM-ed content (pdf) and will download as an `.acsm` file for use with ADE.

This is now available if you update from master. There are no additional command options, if there are attachments, it will be automatically downloaded together with the audiobook into the same folder.

**Comment by wtanksleyjr** [comment]
Thank you, I'll definitely work on that.

-Wm

**Comment by ping** [comment]
Closing because this is now available from the latest v0.8.0 release.
