### ISSUE TITLE
run_tests.sh errors in windows

### ISSUE THREAD

**Issue by jvandervort** [ping/odmpy#40]
Under windows...

```
$ ./run_tests.sh
./run_tests.sh: line 3: coverage: command not found
```

apparently coverage is not in the path when installed normally.

When I run a single coverage command with python -m: TEST_ODM environment var not defined
Apparently this is expected after reading the run_tests.sh, but it would be nice to be able to run these separately.
```
$ python -m coverage run --append -m unittest -v tests.OdmpyTests.test_info
test_info (tests.odmpy_tests.OdmpyTests.test_info)
`odmpy info test.odm` ... ERROR

======================================================================
ERROR: test_info (tests.odmpy_tests.OdmpyTests.test_info)
`odmpy info test.odm`
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\nnn\Documents\dev\odmpy\tests\odmpy_tests.py", line 33, in setUp
    self.test_file = os.environ["TEST_ODM"]
                     ~~~~~~~~~~^^^^^^^^^^^^
  File "<frozen os>", line 679, in __getitem__
KeyError: 'TEST_ODM'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\nnn\Documents\dev\odmpy\tests\odmpy_tests.py", line 35, in setUp
    raise RuntimeError("TEST_ODM environment var not defined.")
RuntimeError: TEST_ODM environment var not defined.

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)
```

```
$ TEST_ODM="test_ref24.odm" python -m coverage run --append -m unittest -v tests.OdmpyTests.test_cover_fail_ref24
```
does work

**Version/Environment**
current head:  0db8641ea1f560d729a7305a7d389d5e3d2af9ca

**Comment by ping** [comment]
coverage was recently added to generate [coverage reports](https://ping.github.io/odmpy/coverage/) as part of testing.

I'm wondering if it's an issue with your environment because the automated tests now include Windows ([example](https://github.com/ping/odmpy/actions/runs/4444988020/jobs/7803704408#step:6:6)) and `run_tests.sh` seem to work fine.

You can run tests separately, you just have to supply the TEST_ODM env var like you already shown. So for that test in the error shown:

```bash
# with the coverage command
TEST_ODM="test1.odm" coverage run --append -m unittest -v tests.OdmpyTests.test_info
# or with coverage as a module
TEST_ODM="test1.odm" python -m coverage run --append -m unittest -v tests.OdmpyTests.test_info
# or just as a regular test
TEST_ODM="test1.odm" python -m unittest -v tests.OdmpyTests.test_info
```

**Comment by jvandervort** [comment]
Yep this works:
$ TEST_ODM="test_ref24.odm" `python -m coverage` run --append -m unittest -v tests.OdmpyTests.test_cover_fail_ref24

But windows does not contain 'coverage' in the path so the script fails on this:
`coverage erase` 
and this
`TEST_ODM="test_ref24.odm" coverage run --append -m unittest -v tests.OdmpyTests.test_cover_fail_ref24` 
without the `python -m`

**Comment by ping** [comment]
> But windows does not contain 'coverage' in the path so the script fails on this: `coverage erase` and this `TEST_ODM="test_ref24.odm" coverage run --append -m unittest -v tests.OdmpyTests.test_cover_fail_ref24` without the `python -m`

You may have to try installing coverage again because Windows does have coverage in the path when installed properly. 
```bash
python3 -m pip -q install -r requirements-dev.txt --upgrade
```

The latest [CI test run](https://github.com/ping/odmpy/actions/runs/4444988020/jobs/7803704408#step:6:6) shows `run_tests.sh` working as-is on Windows. The tests are configured the same way across Ubuntu and Windows.

https://github.com/ping/odmpy/blob/0db8641ea1f560d729a7305a7d389d5e3d2af9ca/.github/workflows/lint-test.yml#L76-L87

**Comment by jvandervort** [comment]
Thanks for the tip, uninstall/reinstall coverage and it added a script into Python311\Scripts folder, so that works now.
Besides a couple deprecation notices, all tests pass.
