### ISSUE TITLE
Does not handle downloads with inordinately long filenames

### ISSUE THREAD

**Issue by berzoidberg** [ping/odmpy#5]
> Traceback (most recent call last):
>   File "/home/zoidberg/.local/bin/odmpy", line 8, in <module>
>     sys.exit(main())
>   File "/home/zoidberg/.local/lib/python3.8/site-packages/odmpy/__main__.py", line 26, in main
>     run()
>   File "/home/zoidberg/.local/lib/python3.8/site-packages/odmpy/odm.py", line 281, in run
>     os.makedirs(book_folder)
>   File "/usr/lib/python3.8/os.py", line 223, in makedirs
>     mkdir(name, mode)
> OSError: [Errno 36] File name too long: "audiobooks/Orson Scott Card's Intergalactic Medicine Show - Orson Scott Card, Edmund R. Schubert, Wayne Wightman, Stefan Rudnicki, Gabrielle De Cuir, Roxanne Hernandez, Arthur Morey, Emily Janice Card, Paul Boehmer, Various Narrators, Claire Bloom, Susan Hanfield, Mary Robinette Kowal, Eric James Stone, Aliette de Bodard, Others"

**Comment by Diegus83** [comment]
This is an OS error because the filename is too long (over 300 characters in this case) so the OS can't create the directory.

I checked this particular odm file and since the book is a compilation there is not author tag, they are all attributed as Contributor, Narrators and one Editor.

It should be easy to handle this error but I'm not sure what the proper way to name the folder and file would be in this case. 

One option would be to arbitrarily cut the directory name to a safe value.

A better one would be to use the Editor's name in the cases where the Author tag is missing. I checked several compilations in the library catalog and they seem to prefer to use the Editor's name where the author would usually be listed. For example John Joseph Adams is the editor of several sci fi collections and his name appears under the title in the search results.

I personally order the books by the following convention "Author Name - Book Name.ext" since that allow Plex + Audiobook agent to recognize it and populate the metadata fields.

**Comment by ping** [comment]
I've chosen to drop all authors from the book folder name when OS error 36 occurs. It's probably not the most ideal solution but hopefully a reasonable enough fix for an edge case like this.

In the reported case, the book folder will now just be ``audiobooks/Orson Scott Card's Intergalactic Medicine Show/``.

**Comment by Diegus83** [comment]
I'm still getting an error related to the long filename but the error code is 63 so the exception is not being caught.

'python3 -m odmpy -v dl -c -k -f -j OrsonScottCardsIntergalacticMedicineS9781482999198.odm' 

```
  File "/Users/diego/Downloads/odmpy-master/odmpy/odm.py", line 282, in run
    os.makedirs(book_folder)
  File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
OSError: [Errno 63] File name too long: "./Orson Scott Card's Intergalactic Medicine Show - Orson Scott Card, Edmund R. Schubert, Wayne Wightman, Stefan Rudnicki, Gabrielle De Cuir, Roxanne Hernandez, Arthur Morey, Emily Janice Card, Paul Boehmer, Various Narrators, Claire Bloom, Susan Hanfield, Mary Robinette Kowal, Eric James Stone, Aliette de Bodard, Others"
```

Seems like the error codes are not standard in different OSs [Popular Errno Codes by Platform](http://www.ioplex.com/~miallen/errcmpp.html)

I changed the OSError value to 63 https://github.com/ping/odmpy/blob/69ba511c44880148b0fac94450a88d76880f2d1b/odmpy/odm.py#L283-L286

The error gets caught and the execution continues but the directory isn't created.
```
  File "/Users/diego/Downloads/odmpy-master/odmpy/odm.py", line 299, in run
    with open(cover_filename, 'wb') as outfile:
FileNotFoundError: [Errno 2] No such file or directory: "./Orson Scott Card's Intergalactic Medicine Show/cover.jpg"
```
I added a new line to create the directory after the error gets caught like this

```python
           book_folder = os.path.join(
                args.download_dir, u'{}'.format(title.replace(os.sep, '-')))
            os.makedirs(book_folder)
```
And the download progresses as expected. 
```
Saved "./Orson Scott Card's Intergalactic Medicine Show/orson-scott-cards-intergalactic-medicine-show-part-12.mp3"
```
It fails to create the merged mp3 file since it is trying to use the full name for the output file.

```
./Orson Scott Card's Intergalactic Medicine Show/Orson Scott Card's Intergalactic Medicine Show - Orson Scott Card, Edmund R. Schubert, Wayne Wightman, Stefan Rudnicki, Gabrielle De Cuir, Roxanne Hernandez, Arthur Morey, Emily Janice Card, Paul Boehmer, Various Narrators, Claire Bloom, Susan Hanfield, Mary Robinette Kowal, Eric James Stone, Aliette de Bodard, Others.mp3: File name too long
ffmpeg exited with the code: 1
```

**Comment by ping** [comment]
@Diegus83 Thanks for the catch. Added a couple more fixes to address the issues you raised.
